require 'rspec'
require 'chess/chessman/pawn'
require 'chess/chessman/knight'
require 'chess/chessman/rook'
require 'chess/chessman/bishop'
require 'chess/chessman/queen'
require 'chess/chessman/king'
require 'chess/board'
